import Head from 'next/head'
import{
  FormBiodataWizard
} from '../components'
import { 
  Row,
} from 'reactstrap';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Row>
          <FormBiodataWizard/>
        </Row>
      </main>
    </div>
  )
}
